[deps]
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
SearchLightSQLite = "21a827c4-482a-11ea-3a19-4d2243a4a2c5"
StipplePlotly = "ec984513-233d-481d-95b0-a3b58b97af2b"
